# Generated by Django 4.1.7 on 2023-03-08 18:55

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model



class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='employees',
            table='employee_employees',
        ),
        # migrations.RunPython(create_superuser),
    ]
