# Generated by Django 4.1.7 on 2023-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employees_chat_id_alter_employees_curator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
