# Generated by Django 4.1.7 on 2023-03-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employees_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='employees',
            name='status_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.status'),
        ),
        migrations.AlterModelTable(
            name='status',
            table='employee_status',
        ),
    ]
