# Generated by Django 4.1.7 on 2023-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanyTable',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name_ru', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'info_AboutCompanyTable',
            },
        ),
        migrations.CreateModel(
            name='AddressesTable',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField()),
                ('address', models.TextField()),
                ('link_2gis', models.TextField()),
            ],
            options={
                'db_table': 'info_AddressesTable',
            },
        ),
    ]
