# Generated by Django 4.1.7 on 2023-03-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faqtable',
            table='faq_faqtable',
        ),
    ]
